src/objects/Incident__c.object
<CustomObject>
    <description>Representing an occurrence of a major incident which can be linked to multiple cases</description>
    <fields>
        <fullName>Console_Label__c</fullName>
        <description>Text entered here will appear on the service agent&apos;s console</description>
        <inlineHelpText>Text entered here will appear on the service agent&apos;s console</inlineHelpText>
        <label>Console Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Note_to_Customers__c</fullName>
        <description>Message to use when advising customers about the incident</description>
        <inlineHelpText>Message to use when advising customers about the incident</inlineHelpText>
        <label>Note to Customers</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Self_service_label__c</fullName>
        <description>Text entered here can be displayed on the company&apos;s web site</description>
        <inlineHelpText>Text entered here can be displayed on the company&apos;s web site (requires adding a component to the site)</inlineHelpText>
        <label>Self service label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>When did the incident start</description>
        <inlineHelpText>When did the incident start</inlineHelpText>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Incident Status (Active, Resolved or Archived)</description>
        <inlineHelpText>Incident Status (Active, Resolved or Archived)</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IncidentController.cls
public with sharing class IncidentController {
    @AuraEnabled
    public static List<Incident__c> getIncidents() {
        return [SELECT Id, Console_Label__c, Note_to_Customers__c, Self_service_label__c, Status__c, Start_date__c 
                FROM Incident__c 
                where Status__c in ('Active','Resolved') 
                order by Status__c ASC, Start_date__c ASC 
                LIMIT 1];
    }
}